### ISSUE TITLE
as an artist i can edit my channel

### ISSUE THREAD

**Issue by serenelion** [Giving-Back-Studio/SacredSoundStudio-funkwhale#52]
i get an error when i click 'save changes' when i am editing my channel

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/67ebb313-bc7b-4c7e-a300-c9dca83cc8f6" />

**Comment by spockNinja** [comment]
Is this still happening after https://github.com/Giving-Back-Studio/SacredSoundStudio-funkwhale/pull/45#issuecomment-2705468195 ?

**Comment by spockNinja** [comment]
@serenelion 

I thought I had this one addressed in #45, but it sounded like there might still be a related error somewhere in the artist channel functionality. I have not been able to reproduce it or track down the corresponding error in GlitchTip.

Could you please confirm that there is still an error occuring along with the time that you triggered the error (so that I can correlate with a GlitchTip error) and any other information you find relevant to tracking down the issue.

Thanks!

**Comment by serenelion** [comment]
@spockNinja si, this issue is still happening for me:

[Wed, 12 Mar 2025 21:08:09 GMT]  ERROR  /assets/index-a84e0805.js:34 E="",C=Math.min()  Unexpected error TypeError: Cannot read properties of undefined (reading 'name')
    at MyChannel.vue:56:39

**Comment by spockNinja** [comment]
Okay, I think I found it. There are several different references to "username" in the system. The one I was using is now allowing spaces, but the one we needed is the "slugified" version that is usable for stable URLs.

This fix is on the way through the staging pipeline now.

**Comment by serenelion** [comment]
I could now get to the edit channel view, however, there is an error when I attempt to save. 

instrument.js:109 [Vue warn]: Error in 1: "TypeError: Cannot read properties of undefined (reading 'full_username')"

instrument.js:109   [Wed, 12 Mar 2025 22:34:35 GMT]  ERROR  /assets/index-f3adeda5.js:34 E="",C=Math.min()  Unexpected error TypeError: Cannot read properties of undefined (reading 'tracks_count')
    at q (DetailBase.vue:291:46)

**Comment by serenelion** [comment]
I wonder if the error may be related to the route i'm being redirected to when i save, it is not the same route that loads when i go to my channel.... 

URL: https://staging.sacredsound.app/channels/aryeartist2
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/7cdca3ff-55e7-42fa-9680-ac3a83557363" />

URL: https://staging.sacredsound.app/channels/arye+artist2
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/40631c76-8581-48ff-a61f-b81beacfcb43" />

**Comment by spockNinja** [comment]
@serenelion 

Thanks, that was all helpful. There were a few spots creating the URL in different ways. It has been DRYed up and now they all use the stable URL. (heading to staging now)
